Add Spanish translation
WowUp/WowUp.Addon pull request #35
Opened 2022-06-19 09:19 UTC by JotaRandom

This add both Latinamerican AND European spanish, it also use the same words that are used in-game for both for they respective language versions

I'm doing it right?

2022-06-19 09:28 UTC, linaori commented
> I'm doing it right?

As I don't have either of the clients, I can't validate this myself, but it looks good. Have you had a chance to test it in-game?

2022-06-19 09:53 UTC, Nils89 requested changes

2022-06-19 09:53 UTC, Nils89 commented on locales/esES.lua
> +local L = LibStub("AceLocale-3.0"):NewLocale("WOWUP", "esES", true, true)
The „, true, true“ needs to be removed. Otherwise this is the default language which will be used if there is no client local file.

2022-06-19 09:53 UTC, Nils89 commented on locales/esMX.lua
> +local L = LibStub("AceLocale-3.0"):NewLocale("WOWUP", "esMX", true, true)
The „, true, true“ needs to be removed. Otherwise this is the default language which will be used if there is no client local file.

2022-06-19 09:57 UTC, Nils89 requested changes

2022-06-19 09:57 UTC, Nils89 commented on locales/esES.lua
> +
Here needs to be added this line 
`if not L then return end `

2022-06-19 09:57 UTC, Nils89 commented on locales/esMX.lua
> +
Here needs to be added this line 
`if not L then return end `

2022-06-19 10:03 UTC, Nils89 commented
Both files need to be added to the .toc file as well (under the last local file)

2022-06-20 00:04 UTC, JotaRandom commented
I did a commit with the changes [853de3d9f64f61c082f309b8e972ce1e9ce7eff8]

2022-06-20 07:26 UTC, merged